package it.unibo.project.input.api;

public enum Action {
    CHANGE_SCENE_TO_MENU,
    CHANGE_SCENE_TO_SHOP,
    CHANGE_SCENE_TO_GAME,
    CHANGE_SCENE_TO_OVER,
    CHANGE_SCENE_TO_VICTORY,
    EXIT_APP,
    MOVE_PLAYER_UP,
    MOVE_PLAYER_DOWN,
    MOVE_PLAYER_LEFT,
    MOVE_PLAYER_RIGHT,
}
